title: Janne Lumijärvi's Blog
#email: janne.kr.lumijarvi@gmail.com
description: >-
  Just another programming blog.
baseurl: ""
url: "https://jlumijarvi.github.io"
github_username:  jlumijarvi

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

excerpt_separator: ""
