title: Janne Lumijärvi's Blog
#email: janne.kr.lumijarvi@gmail.com
description: >-
  Just another programming blog.
baseurl: ""
url: "https://jlumijarvi.github.io"
github_username: jlumijarvi
linkedin: jannelumijarvi
google_analytics: UA-115091953-1

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

disqus:
  shortname: jlumijarvi-github-io

excerpt_separator: ""
