title: Janne Lumijärvi's Blog
#email: janne.kr.lumijarvi@gmail.com
description: >-
  Just another programming blog.
baseurl: ""
url: "https://jlumijarvi.github.io"
github_username: jlumijarvi
linkedin_username: jannelumijarvi
google_analytics: UA-115091953-1

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

disqus:
  shortname: jlumijarvi-github-io

excerpt_separator: ""
